name: Build to Maven Local

on:
  push:
    branches:
      - '*'
      - '!ci_test_*'
    tags-ignore:
      - '*'
  pull_request:
    branches:
      - '*'
      - '!ci_test_*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          link-to-sdk: true

      - name: Set custom environment variable
        run: echo "GITHUB_REF_NAME=$GITHUB_REF_NAME" >> $GITHUB_ENV

      - name: Compile to maven local
        env:
          VERSION_NAME: ${{ env.GITHUB_REF_NAME }}
        run: bash ./gradlew jxlcoder:publishToMavenLocal